services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: neko_admin
      POSTGRES_PASSWORD: meowmeow123
      POSTGRES_DB: nekolook
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - neko-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - neko-network

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - neko-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      NODE_ENV: development
    networks:
      - neko-network

networks:
  neko-network:
    driver: bridge
